// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektNalozi.Models;

namespace ProjektNalozi.Migrations
{
    [DbContext(typeof(PutniNalogDbContext))]
    [Migration("20201219181941_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ProjektNalozi.Models.PutniNalog", b =>
                {
                    b.Property<int>("PutniNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BrojPutnika")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Komentar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Odrediste")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Polazak")
                        .HasColumnType("datetime2");

                    b.Property<string>("Polaziste")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Povratak")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prijevoz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazlogPutovanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistracijaVozila")
                        .HasColumnType("varchar(8)");

                    b.HasKey("PutniNalogId");

                    b.ToTable("PutniNalozi");

                    b.HasData(
                        new
                        {
                            PutniNalogId = 1,
                            BrojPutnika = 1,
                            Email = "ivan@gmail.com",
                            Komentar = "",
                            Odrediste = "Osijek",
                            Polazak = new DateTime(2018, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Polaziste = "Zagreb",
                            Povratak = new DateTime(2018, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prijevoz = "Službeni automobil",
                            RazlogPutovanja = "Moralo se",
                            RegistracijaVozila = "ZG2342CA"
                        },
                        new
                        {
                            PutniNalogId = 2,
                            BrojPutnika = 2,
                            Email = "ivan@gmail.com",
                            Komentar = "eto",
                            Odrediste = "Osijek",
                            Polazak = new DateTime(2020, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Polaziste = "Zagreb",
                            Povratak = new DateTime(2020, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prijevoz = "Službeni automobil",
                            RazlogPutovanja = "Moralo se",
                            RegistracijaVozila = "ZG2342CA"
                        },
                        new
                        {
                            PutniNalogId = 3,
                            BrojPutnika = 3,
                            Email = "ivan@gmail.com",
                            Komentar = "",
                            Odrediste = "Osijek",
                            Polazak = new DateTime(2019, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Polaziste = "Zagreb",
                            Povratak = new DateTime(2019, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prijevoz = "Službeni automobil",
                            RazlogPutovanja = "Moralo se",
                            RegistracijaVozila = "ZG2342CA"
                        },
                        new
                        {
                            PutniNalogId = 4,
                            BrojPutnika = 1,
                            Email = "ivan@gmail.com",
                            Komentar = "",
                            Odrediste = "Osijek",
                            Polazak = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Polaziste = "Zagreb",
                            Povratak = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prijevoz = "Službeni automobil",
                            RazlogPutovanja = "Moralo se",
                            RegistracijaVozila = "ZG2342CA"
                        });
                });

            modelBuilder.Entity("ProjektNalozi.Models.Putnik", b =>
                {
                    b.Property<int>("PutnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PutnikId");

                    b.ToTable("Putnici");

                    b.HasData(
                        new
                        {
                            PutnikId = 1,
                            Ime = "Marko",
                            Prezime = "Markić"
                        },
                        new
                        {
                            PutnikId = 2,
                            Ime = "Ivan",
                            Prezime = "Ivanić"
                        },
                        new
                        {
                            PutnikId = 3,
                            Ime = "Luna",
                            Prezime = "Lunić"
                        },
                        new
                        {
                            PutnikId = 4,
                            Ime = "Karla",
                            Prezime = "Karlić"
                        });
                });

            modelBuilder.Entity("ProjektNalozi.Models.PutnikovNalog", b =>
                {
                    b.Property<int>("PutnikId")
                        .HasColumnType("int");

                    b.Property<int>("PutniNalogId")
                        .HasColumnType("int");

                    b.HasKey("PutnikId", "PutniNalogId");

                    b.HasIndex("PutniNalogId");

                    b.ToTable("PutnikoviNalozi");

                    b.HasData(
                        new
                        {
                            PutnikId = 1,
                            PutniNalogId = 1
                        },
                        new
                        {
                            PutnikId = 1,
                            PutniNalogId = 2
                        },
                        new
                        {
                            PutnikId = 1,
                            PutniNalogId = 3
                        },
                        new
                        {
                            PutnikId = 2,
                            PutniNalogId = 2
                        },
                        new
                        {
                            PutnikId = 3,
                            PutniNalogId = 3
                        },
                        new
                        {
                            PutnikId = 4,
                            PutniNalogId = 3
                        },
                        new
                        {
                            PutnikId = 3,
                            PutniNalogId = 4
                        });
                });

            modelBuilder.Entity("ProjektNalozi.Models.PutnikovNalog", b =>
                {
                    b.HasOne("ProjektNalozi.Models.PutniNalog", "PutniNalog")
                        .WithMany("PutnikoviNalozi")
                        .HasForeignKey("PutniNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektNalozi.Models.Putnik", "Putnik")
                        .WithMany("PutnikoviNalozi")
                        .HasForeignKey("PutnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Putnik");

                    b.Navigation("PutniNalog");
                });

            modelBuilder.Entity("ProjektNalozi.Models.PutniNalog", b =>
                {
                    b.Navigation("PutnikoviNalozi");
                });

            modelBuilder.Entity("ProjektNalozi.Models.Putnik", b =>
                {
                    b.Navigation("PutnikoviNalozi");
                });
#pragma warning restore 612, 618
        }
    }
}
